### PR TITLE
fixes for failed uploads breaking /file/edit page

### LINKED ISSUE #1928: Error on /file/edit
I keep getting an error when I go to https://www.dreamwidth.org/file/edit

[Error: Column 'height' cannot be null at /home/dw/production/cgi-bin/DW/Media.pm line 62. @ va-web04]

I've gotten this message since uploading some pics apparently failed. I got this on /file/new then:

Unable to instantiate file in MogileFS. at /home/dw/production/cgi-bin/DW/Controller/API/Media.pm line 71 on /file/new

The uploader has been working fine since then but /file/edit won't.

### PR DESCRIPTION
**Pull request by kareila**
This fix is in three stages as detailed in each individual commit:

- Provide a more informative error if get_file_data fails in the _resize method.

- Print the error to the log instead, and hide any problematic images from the user.

- Reorder operations in upload_media to prevent the problem from happening again.

Fixes #1928.

### CODE REVIEW

File: cgi-bin/DW/Media.pm [hunk 1]
```diff
@@ -202,8 +202,17 @@ sub get_active_for_user {
     return () unless $rows && ref $rows eq 'ARRAY';
 
     # construct media objects for each of the items and return that
-    return sort { $b->logtime <=> $a->logtime }
-           map { DW::Media->new( user => $u, mediaid => $_, %opts ) } @$rows;
+    my @media;
+    foreach ( @$rows ) {
+        # use eval to catch croaks
+        my $obj = eval { DW::Media->new( user => $u, mediaid => $_, %opts ) };
```
Comment (zorkian) [inline cgi-bin/DW/Media.pm]: I sort of wonder what the best way to actually handle errors in Perl is. If the library hits a problem, croak? And let upstreams catch it? Or return undefs and errstrs? I don't even know anymore and we use every single paradigm in the DW code...

**Comment by zorkian** [comment]
I'm slightly dubious about inverting the order here -- i.e., this just abandons things in the other way, but it's at least in a way that doesn't show up to the user and we can handle internally (running scrubbers to clean up unlinked files).

So, it's a better user experience and so I'll merge. It would be nice to actually catch errors in either process and do a total cleanup, but we don't need to for now.
