### PR TITLE
[#1111] Track captcha failure/success

### LINKED ISSUE #1111: Monitor captcha failure rate
We should monitor the captcha fail rate (useful indicator of service problem or potentially bot attack)

### PR DESCRIPTION
**Pull request by afuna**
Fixes #1111.

### CODE REVIEW

**Comment by afuna** [comment]
Adds as tags the captcha type (textcapctcha/recaptcha) and page type the captcha is on (not url -- but whether it's there for lostinfo, for anon comments, etc)

File: cgi-bin/DW/Captcha.pm [hunk 1]
```diff
@@ -209,10 +209,14 @@ sub validate {
 
     my $err_ref = $opts{err_ref};
 
-    if ( $self->challenge ) {
-        return 1 if $self->_validate;
+                    # captcha type, page captcha appeared on
+    my $stat_tags = [ (ref $self)->name, "page:" . $self->page ];
```
Comment (zorkian) [inline cgi-bin/DW/Captcha.pm]: What is `name` and `page` here? We can't insert completely arbitrary tags, they have to fit some requirements -- basically `[a-z0-9_-:.]` or something.

Comment (afuna) [inline cgi-bin/DW/Captcha.pm]: name can be “recaptcha", “textcaptcha"

page can be any of the keys in CAPTCHA_FOR in our config, currently:
“create”, “lost info”, “validate_openid”, “support_submit_anon”, “anon
post”, “autopost”, “comment_html_anon”, "comment_html_auth"


On Sat, Mar 7, 2015, at 10:28 PM, Mark Smith wrote:
> In cgi-bin/DW/Captcha.pm[1]:


> > @@ -209,10 +209,14 @@ sub validate {
>
>      my $err_ref = $opts{err_ref};
>
> -    if ( $self->challenge ) {
> -        return 1 if $self->_validate;
> +                    # captcha type, page captcha appeared on
> +    my $stat_tags = [ (ref $self)->name, "page:" . $self->page ];
>      What is name and page here? We can't insert completely arbitrary
>      tags, they have to fit some requirements -- basically
>      [a-z0-9_-:.] or something.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/dreamwidth/dw-free/pull/1285#discussion_r26002701
  2. https://github.com/dreamwidth/dw-free/pull/1285/files#r26002701
