### PR TITLE
Return to original thread view after commenting/editing

### LINKED ISSUE #2717: possibly wrong redirect after posting from new comment preview when viewing a single thread
Several people have raised this in dw_maint, but I'll summarize it here:

Before the change, the return link argument was of the form `?thread=(######)&posted=1#cmt(######)` which just loaded the relevant thread you were commenting on. 

Now it returns to `?view=(######)&posted=1#cmt(######)` which loads the whole page from the top. 

If there are a lot of comments on the page, this can be a lot slower to load, in addition to losing your place on the page.

### PR DESCRIPTION
**Pull request by nfagerlund**
Fixes #2717

- The quick-reply has always (?) had a hidden `viewing_thread` field that keeps a record of which thread you were viewing when you hit "reply", and we try to redirect you there after posting. 
- The talkform has never had that, so if you used "more options", you'd redirect to the main entry page when done. Same for editing comments or opening a reply link in a new tab (or with no JS). 
- The old previewform, however, used to just copy over every form field it didn't recognize into a hidden input. So if you previewed FROM the quick-reply, you'd get the quick-reply behavior! 

So: the return-to-thread after preview behavior broke because I replaced the previewform with the talkform, which didn't know how to deal with the `viewing_thread` field and doesn't duplicate whatever random garbage you huck at it.

The fourth commit in this PR fixes the reported bug.

The first three commits are cleanups and docs. 

The fifth and sixth commits enable return-to-thread for edit links and reply links, which have never supported that before, but really why shouldn't they.

### CODE REVIEW

**Comment by nfagerlund** [comment]
(BTW: If you want to fix this quickly and there are any questions about the approach in commits 5 and 6, you can manually merge just the first four! They don't depend on the last two, and they bring us up to parity with the previous behavior.)

**Comment by rahaeli** [comment]
....that's kind of an amazing case of "bug becomes unintentional feature". (I agree that adding the return-to-thread behavior elsewhere is a good idea.)

File: cgi-bin/DW/Controller/Talk.pm [hunk 1]
```diff
@@ -8,6 +8,154 @@ use Carp;
 
 DW::Routing->register_string( '/talkpost_do', \&talkpost_do_handler, app => 1 );
 
+# I think this canon isn't written down anywhere else, so HWAET: I sing a record
+# of every damn form field that comes through in reply form POSTs. -NF
```
Comment (zorkian) [inline cgi-bin/DW/Controller/Talk.pm:12]: oh my lord this comment T_T

this is why we can't have nice things. or, alternately: this is why the world is moving towards static typing as a necessity for building software at anything beyond toy-scale.
